import assert from "node:assert/strict";
import test from "node:test";
import { addTaskCard, buildBatchPayload, createTaskCard, removeTaskCard, validateTaskCards } from "./taskAssignmentCards.mjs";
const card = (overrides = {}) => ({ cardId: "card-1", title: "Việc một", description: "Mô tả một", requirements: ["Yêu cầu một"], dueDate: "2026-09-30", dueTime: "17:30", collaboratorIds: [], watcherIds: [], priority: "normal", recurrenceFrequency: null, recurrenceEndsOn: null, attachment: null, ...overrides });
test("default cards are independent and have stable keys", () => { const first = createTaskCard("card-1"); const second = createTaskCard("card-2"); assert.equal(first.cardId, "card-1"); assert.equal(second.cardId, "card-2"); assert.notEqual(first, second); assert.deepEqual(first.requirements, [""]); assert.notEqual(first.requirements, second.requirements); });
test("add task creates a clean card and never exceeds twenty", () => { const cards = [card()]; const added = addTaskCard(cards, "card-2"); assert.equal(added.length, 2); assert.equal(added[1].title, ""); assert.notEqual(added[1].requirements, cards[0].requirements); assert.equal(addTaskCard(Array.from({ length: 20 }, (_, index) => card({ cardId: `card-${index}` })), "card-21").length, 20); });
test("remove task preserves one card and closes the middle gap", () => { const remaining = removeTaskCard([card({ cardId: "one" }), card({ cardId: "two" }), card({ cardId: "three" })], 1); assert.deepEqual(remaining.map((item) => item.cardId), ["one", "three"]); assert.equal(removeTaskCard([card()], 0).length, 1); });
test("validation points to the first invalid task and field", () => { assert.deepEqual(validateTaskCards([card(), card({ cardId: "card-2", title: "" })]), [{ taskIndex: 1, field: "title", message: "Việc 2 chưa có Tên công việc" }]); });
test("batch payload preserves shared recipient and card order without notes", () => { const payload = buildBatchPayload({ batchId: "batch-1", departmentId: "dept-1", assigneeId: "user-1", cards: [card(), card({ cardId: "card-2", title: "Việc hai" })] }); assert.equal(payload.mode, "batch"); assert.equal(payload.departmentId, "dept-1"); assert.equal(payload.assigneeId, "user-1"); assert.deepEqual(payload.tasks.map((item) => item.title), ["Việc một", "Việc hai"]); assert.equal("notes" in payload.tasks[0], false); });
