import "server-only";
import { serverSupabase } from "@/lib/serverSupabase";
import { isSystemAdminStaff, sortStaffRows } from "@/lib/staffOrdering";
export const workScheduleRepository = {
  async allPeople() { const { data, error } = await serverSupabase.from("staff_users").select("id,username,full_name,roles(code),job_titles(code)").eq("active", true).order("full_name"); return error ? { ok: false as const, error } : { ok: true as const, people: sortStaffRows(data ?? []).filter((person) => !isSystemAdminStaff(person)) }; },
  async person(id: string) { const { data, error } = await serverSupabase.from("staff_users").select("id,username,full_name,roles(code),job_titles(code)").eq("id", id).eq("active", true).maybeSingle(); return error ? { ok: false as const, error } : { ok: true as const, person: data }; },
  async list(from: string, to: string, participantId?: string) { let query = serverSupabase.from("work_schedules").select("id,work_date,end_date,plan_type,start_time,end_time,title,location,notes,participant_ids,created_by,creator:staff_users!work_schedules_created_by_fkey(full_name)").lte("work_date", to).gte("end_date", from); if (participantId) query = query.contains("participant_ids", [participantId]); const { data, error } = await query.order("work_date").order("start_time"); return error ? { ok: false as const, error } : { ok: true as const, rows: data ?? [] }; },
  async save(actorId: string, input: { id?: string; workDate: string; endDate: string; planType: "work" | "business" | "event"; startTime: string | null; endTime: string | null; title: string; location: string | null; notes: string | null; participantIds: string[] }, isAdmin = false) { const payload = { work_date: input.workDate, end_date: input.endDate, plan_type: input.planType, start_time: input.startTime, end_time: input.endTime, title: input.title, location: input.location, notes: input.notes, participant_ids: input.participantIds, ...(input.id ? {} : { created_by: actorId }), updated_at: new Date().toISOString() }; let query = input.id ? serverSupabase.from("work_schedules").update(payload).eq("id", input.id) : serverSupabase.from("work_schedules").insert({ ...payload, created_by: actorId }); if (input.id && !isAdmin) query = query.eq("created_by", actorId); const { data, error } = await query.select().single(); return error ? { ok: false as const, error } : { ok: true as const, row: data }; },
  async remove(actorId: string, id: string, isAdmin = false) { let query = serverSupabase.from("work_schedules").delete().eq("id", id); if (!isAdmin) query = query.eq("created_by", actorId); const { error } = await query; return error ? { ok: false as const, error } : { ok: true as const }; },
  async people() { const { data, error } = await serverSupabase.from("staff_users").select("id,username,full_name,roles(code),job_titles(code)").eq("active", true).order("full_name"); return error ? { ok: false as const, error } : { ok: true as const, people: sortStaffRows(data ?? []).filter((p) => !isSystemAdminStaff(p) && ["tong_bien_tap", "pho_tong_bien_tap"].includes((p.roles as {code?: string}|null)?.code ?? "") || ((p.job_titles as {code?: string}|null)?.code ?? "").startsWith("truong_phong") || ((p.job_titles as {code?: string}|null)?.code ?? "").startsWith("phong_vien")) }; },
};
