import "server-only";
import { serverSupabase } from "@/lib/serverSupabase";
import { sortStaffRows } from "@/lib/staffOrdering";
export const workScheduleRepository = {
  async allPeople() { const { data, error } = await serverSupabase.from("staff_users").select("id,full_name,roles(code),job_titles(code)").eq("active", true).order("full_name"); return error ? { ok: false as const, error } : { ok: true as const, people: sortStaffRows(data ?? []) }; },
  async list(from: string, to: string) { const { data, error } = await serverSupabase.from("work_schedules").select("id,work_date,start_time,end_time,title,location,notes,participant_ids,created_by,creator:staff_users!work_schedules_created_by_fkey(full_name)").gte("work_date", from).lte("work_date", to).order("work_date").order("start_time"); return error ? { ok: false as const, error } : { ok: true as const, rows: data ?? [] }; },
  async save(actorId: string, input: { id?: string; workDate: string; startTime: string | null; endTime: string | null; title: string; location: string | null; notes: string | null; participantIds: string[] }) { const payload = { work_date: input.workDate, start_time: input.startTime, end_time: input.endTime, title: input.title, location: input.location, notes: input.notes, participant_ids: input.participantIds, created_by: actorId, updated_at: new Date().toISOString() }; const query = input.id ? serverSupabase.from("work_schedules").update(payload).eq("id", input.id).select().single() : serverSupabase.from("work_schedules").insert(payload).select().single(); const { data, error } = await query; return error ? { ok: false as const, error } : { ok: true as const, row: data }; },
  async remove(id: string) { const { error } = await serverSupabase.from("work_schedules").delete().eq("id", id); return error ? { ok: false as const, error } : { ok: true as const }; },
  async people() { const { data, error } = await serverSupabase.from("staff_users").select("id,full_name,roles(code),job_titles(code)").eq("active", true).order("full_name"); return error ? { ok: false as const, error } : { ok: true as const, people: sortStaffRows(data ?? []).filter((p) => ["tong_bien_tap", "pho_tong_bien_tap"].includes((p.roles as {code?: string}|null)?.code ?? "") || ((p.job_titles as {code?: string}|null)?.code ?? "").startsWith("truong_phong") || ((p.job_titles as {code?: string}|null)?.code ?? "").startsWith("phong_vien")) }; },
};
