#!/usr/bin/env bash
set -Eeuo pipefail
: "${THOIDAI_SOURCE_REPO:=/opt/thoidai-work}"; : "${THOIDAI_WORKTREE_ROOT:=/opt/worktrees}"; : "${THOIDAI_LSOF_TIMEOUT_SEC:=2}"
size(){ [[ -e "$1" ]] && du -sx --bytes -- "$1" 2>/dev/null | awk 'NR==1{print $1}' || echo 0; }
printf 'WORKTREE LIFECYCLE ADOPTION REPORT\n'; total=0; managed=0; unmanaged=0; protected=0; active=0; shrink=0; remove=0; unknown=0; safe_reclaim=0
while IFS= read -r path; do
 total=$((total+1)); branch=$(git -C "$path" symbolic-ref --short -q HEAD || echo detached); head=$(git -C "$path" rev-parse HEAD 2>/dev/null || echo UNKNOWN); upstream=$(git -C "$path" rev-parse --abbrev-ref '@{upstream}' 2>/dev/null || echo NONE); clean=YES; [[ -n "$(git -C "$path" status --porcelain 2>/dev/null)" ]] && clean=NO; ahead=UNKNOWN; behind=UNKNOWN; recoverable=NO; if [[ "$upstream" != NONE ]]; then counts=$(git -C "$path" rev-list --left-right --count "$upstream...HEAD" 2>/dev/null || echo 'UNKNOWN UNKNOWN'); read -r behind ahead <<<"$counts"; [[ "$ahead" == 0 ]] && recoverable=YES; fi; last=$(git -C "$path" log -1 --format=%cI 2>/dev/null || echo UNKNOWN); epoch=$(git -C "$path" log -1 --format=%ct 2>/dev/null || echo 0); age=UNKNOWN; [[ "$epoch" =~ ^[0-9]+$ && "$epoch" != 0 ]] && age=$((($(date +%s)-epoch)/86400)); total_bytes=$(size "$path"); node=$(size "$path/node_modules"); next=$(size "$path/.next"); cache=$(size "$path/.next/cache"); source=$((total_bytes-node-next)); ((source<0)) && source=0; proc=NO; pgrep -af -- "$path" 2>/dev/null | grep -v 'worktree-adoption-audit' | grep -q . && proc=YES; open=UNKNOWN; if [ "${THOIDAI_AUDIT_OPEN_FILES:-0}" = 1 ] && command -v lsof >/dev/null; then timeout "$THOIDAI_LSOF_TIMEOUT_SEC" lsof +D "$path" 2>/dev/null | tail -n +2 | grep -q . && open=YES || [[ ${PIPESTATUS[0]} -eq 124 ]] && open=UNKNOWN; else open=UNKNOWN; fi; referenced=NO; grep -R -F -l -- "$path" /etc/systemd/system /etc/nginx /opt/ops/thoidai-work 2>/dev/null | grep -q . && referenced=YES
 state=UNKNOWN; reason=ambiguous; if [[ "$path" == "$THOIDAI_SOURCE_REPO" || "$referenced" == YES ]]; then state=PROTECTED; reason=production-or-config-reference; protected=$((protected+1)); elif [[ "$proc" == YES || "$open" == YES ]]; then state=ACTIVE; reason=process-or-open-file; active=$((active+1)); elif [[ "$clean" == YES && "$recoverable" == YES && "$open" == NO ]]; then state=READY_FOR_SHRINK; reason=clean-pushed-inactive; shrink=$((shrink+1)); safe_reclaim=$((safe_reclaim+node+next)); else unknown=$((unknown+1)); fi; [[ -f "$path/.thoidai-lifecycle" ]] && managed=$((managed+1)) || unmanaged=$((unmanaged+1)); printf 'path=%s\tbranch=%s\thead=%s\tupstream=%s\tclean=%s\tahead=%s\tbehind=%s\tremote_recoverable=%s\tlast_commit=%s\tage_days=%s\ttotal=%s\tsource=%s\tnode_modules=%s\tnext=%s\tnext_cache=%s\tproduction_referenced=%s\tactive_process_cwd=%s\topen_files=%s\trecommended=%s\treason=%s\n' "$path" "$branch" "$head" "$upstream" "$clean" "$ahead" "$behind" "$recoverable" "$last" "$age" "$total_bytes" "$source" "$node" "$next" "$cache" "$referenced" "$proc" "$open" "$state" "$reason"
done < <(git -C "$THOIDAI_SOURCE_REPO" worktree list --porcelain | awk '/^worktree /{print substr($0,10)}')
printf 'Total worktrees: %s\nManaged: %s\nUnmanaged: %s\nPROTECTED: %s\nACTIVE: %s\nREADY_FOR_SHRINK: %s\nREADY_FOR_REMOVE: %s\nUNKNOWN: %s\nTotal safe SHRINK reclaim: %s\nProduction changed: NO\n' "$total" "$managed" "$unmanaged" "$protected" "$active" "$shrink" "$remove" "$unknown" "$safe_reclaim"