"use client";
import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import AppNav from "@/components/AppNav";
import { useAuth } from "@/lib/auth";
import type { AccountPreferences } from "@/lib/accountPreferences";
type Props={userLabel:string;roleName:string;email:string|null;phone:string|null;username:string|null;avatarUrl:string|null;preferences:AccountPreferences;mustChangePassword?:boolean};
export default function AccountShell(p:Props){
 const router=useRouter();const {logout,refreshSession}=useAuth();const inputRef=useRef<HTMLInputElement>(null);const [name,setName]=useState(p.userLabel);const [email,setEmail]=useState(p.email??"");const [phone,setPhone]=useState(p.phone??"");const [prefs,setPrefs]=useState(p.preferences);const [avatar,setAvatar]=useState(p.avatarUrl);const [currentPassword,setCurrentPassword]=useState("");const [newPassword,setNewPassword]=useState("");const [confirmPassword,setConfirmPassword]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
 const request=async(path:string,body:object)=>{setBusy(true);setMessage("");try{const r=await fetch(path,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json().catch(()=>null) as {error?:string;message?:string}|null;if(!r.ok)throw new Error(d?.error??"Không thể cập nhật.");setMessage(d?.message??"Đã cập nhật.");return true;}catch(e){setMessage(e instanceof Error?e.message:"Không thể cập nhật.");return false;}finally{setBusy(false);}};
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(await request("/api/account/profile",{fullName:name,email,phone,preferences:prefs}))await refreshSession();};
 const upload=async(file:File)=>{if(file.size>2*1024*1024){setMessage("Ảnh vượt quá 2 MB. Vui lòng chọn ảnh có dung lượng nhỏ hơn.");if(inputRef.current)inputRef.current.value="";return;}setBusy(true);setMessage("");try{const form=new FormData();form.set("avatar",file);const r=await fetch("/api/account/avatar",{method:"POST",body:form});const text=await r.text();let d:{error?:string;message?:string;avatarUrl?:string}={};try{d=JSON.parse(text) as typeof d;}catch{if(r.status===413)throw new Error("Ảnh tải lên quá lớn. Vui lòng chọn ảnh tối đa 2 MB.");throw new Error("Máy chủ không thể xử lý ảnh. Vui lòng thử lại.");}if(!r.ok)throw new Error(d.error??(r.status===413?"Ảnh tải lên quá lớn. Vui lòng chọn ảnh tối đa 2 MB.":"Không thể tải ảnh lên."));setAvatar(d.avatarUrl??null);setMessage(d.message??"Đã cập nhật ảnh đại diện.");await refreshSession();}catch(e){setMessage(e instanceof Error?e.message:"Không thể tải ảnh lên.");}finally{setBusy(false);if(inputRef.current)inputRef.current.value="";}};
 const remove=async()=>{setBusy(true);try{const r=await fetch("/api/account/avatar",{method:"DELETE"});const d=await r.json() as {error?:string;message?:string};if(!r.ok)throw new Error(d.error);setAvatar(null);setMessage(d.message??"Đã xóa ảnh đại diện.");await refreshSession();}catch(e){setMessage(e instanceof Error?e.message:"Không thể xóa ảnh.");}finally{setBusy(false);}};
 const changePassword=async(e:React.FormEvent)=>{e.preventDefault();if(newPassword!==confirmPassword)return setMessage("Mật khẩu xác nhận không khớp.");if(await request("/api/account/password",{currentPassword,newPassword,confirmPassword})){logout();router.replace("/login");}};
 const initials=name.trim().split(/\s+/).slice(-2).map(w=>w[0]).join("").toUpperCase();
 return <div className="min-h-screen bg-slate-50 px-3 py-4 text-slate-900"><div className="flex w-full flex-col gap-4 lg:flex-row"><AppNav currentPath="/account" userLabel={name} onLogout={()=>{logout();router.replace("/login");}}/><main className="min-w-0 flex-1 space-y-4"><section className="rounded-xl border bg-white p-4 shadow-sm sm:p-6"><p className="text-xs font-semibold uppercase tracking-wide text-orange-600">Tài khoản</p><h1 className="mt-2 text-2xl font-bold tracking-tight">Cá nhân hóa tài khoản</h1><p className="mt-1 text-sm text-slate-600">Cập nhật thông tin liên hệ, ảnh đại diện và cách hiển thị phù hợp với bạn.</p>{message?<p role="status" aria-live="polite" className="mt-4 rounded-lg border border-orange-200 bg-orange-50 p-3 text-sm text-orange-950">{message}</p>:null}
 <div className="mt-6 flex flex-wrap items-center gap-4 rounded-xl border border-slate-200 bg-slate-50/70 p-4"><div className="flex h-24 w-24 shrink-0 items-center justify-center overflow-hidden rounded-full border-4 border-orange-100 bg-orange-50 text-2xl font-bold text-orange-700">{avatar?<img src={avatar} alt={`Ảnh đại diện của ${name}`} className="h-full w-full object-cover"/>:initials}</div><div><p className="font-semibold">Ảnh đại diện</p><p className="mb-3 text-sm text-slate-500">JPG, PNG hoặc WebP · tối đa 2 MB</p><input ref={inputRef} type="file" accept="image/jpeg,image/png,image/webp" className="sr-only" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);}}/><div className="flex flex-wrap gap-2"><button type="button" disabled={busy} onClick={()=>inputRef.current?.click()} className="min-h-11 rounded-lg bg-orange-600 px-4 py-2 font-semibold text-white hover:bg-orange-700 disabled:opacity-50">Chọn ảnh</button>{avatar?<button type="button" disabled={busy} onClick={()=>void remove()} className="min-h-11 rounded-lg border border-slate-300 bg-white px-4 py-2 font-semibold text-slate-700 hover:border-orange-300 hover:bg-orange-50 disabled:opacity-50">Xóa ảnh</button>:null}</div></div></div>
 <form onSubmit={save} className="mt-6 grid gap-4 sm:grid-cols-2"><label className="grid gap-1.5 text-sm font-semibold">Họ và tên<input value={name} onChange={e=>setName(e.target.value)} required maxLength={120} className="min-h-11 rounded-lg border px-3 py-2 font-normal"/></label><label className="grid gap-1.5 text-sm font-semibold">Tên đăng nhập<input value={p.username??""} disabled className="min-h-11 rounded-lg border bg-slate-100 px-3 py-2 font-normal text-slate-500"/></label><label className="grid gap-1.5 text-sm font-semibold">Thư điện tử<input type="email" value={email} onChange={e=>setEmail(e.target.value)} className="min-h-11 rounded-lg border px-3 py-2 font-normal"/></label><label className="grid gap-1.5 text-sm font-semibold">Số điện thoại<input value={phone} onChange={e=>setPhone(e.target.value)} className="min-h-11 rounded-lg border px-3 py-2 font-normal"/></label><p className="text-sm text-slate-500 sm:col-span-2">Vai trò: <span className="font-semibold text-slate-700">{p.roleName}</span></p><div className="border-t pt-5 sm:col-span-2"><h2 className="text-lg font-bold">Tùy chọn hiển thị</h2><p className="mt-1 text-sm text-slate-500">Điều chỉnh mật độ và chuyển động của giao diện theo nhu cầu.</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="flex items-start gap-3 rounded-xl border p-3 transition hover:border-orange-200 hover:bg-orange-50/40"><input type="checkbox" checked={prefs.compactMode} onChange={e=>setPrefs({...prefs,compactMode:e.target.checked})} className="mt-1 h-5 w-5 accent-orange-600"/><span><b>Hiển thị gọn</b><small className="block text-slate-500">Giảm khoảng cách để xem nhiều nội dung hơn.</small></span></label><label className="flex items-start gap-3 rounded-xl border p-3 transition hover:border-orange-200 hover:bg-orange-50/40"><input type="checkbox" checked={prefs.reduceMotion} onChange={e=>setPrefs({...prefs,reduceMotion:e.target.checked})} className="mt-1 h-5 w-5 accent-orange-600"/><span><b>Giảm hiệu ứng chuyển động</b><small className="block text-slate-500">Giúp giao diện ổn định, ít chuyển động.</small></span></label><label className="grid gap-1.5 text-sm font-semibold sm:col-span-2">Chế độ lịch mặc định<select value={prefs.defaultScheduleView} onChange={e=>setPrefs({...prefs,defaultScheduleView:e.target.value as AccountPreferences["defaultScheduleView"]})} className="min-h-11 rounded-lg border px-3 py-2 font-normal"><option value="day">Ngày</option><option value="week">Tuần</option><option value="month">Tháng</option></select></label></div></div><button disabled={busy} className="min-h-11 rounded-lg bg-orange-600 px-4 py-2 font-semibold text-white hover:bg-orange-700 disabled:opacity-50 sm:col-span-2 sm:justify-self-start">{busy ? "Đang lưu..." : "Lưu thông tin và tùy chọn"}</button></form></section>
 <section className="rounded-xl border bg-white p-4 shadow-sm sm:p-6"><h2 className="text-xl font-bold">Đổi mật khẩu</h2><p className="mt-1 text-sm text-slate-500">Dùng mật khẩu dài tối thiểu 8 ký tự và không chia sẻ cho người khác.</p><form onSubmit={changePassword} className="mt-5 grid max-w-xl gap-3"><label className="grid gap-1.5 text-sm font-semibold">Mật khẩu hiện tại<input type="password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)} required autoComplete="current-password" className="min-h-11 rounded-lg border px-3 py-2 font-normal"/></label><label className="grid gap-1.5 text-sm font-semibold">Mật khẩu mới<input type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} required minLength={8} autoComplete="new-password" className="min-h-11 rounded-lg border px-3 py-2 font-normal"/></label><label className="grid gap-1.5 text-sm font-semibold">Nhập lại mật khẩu mới<input type="password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} required minLength={8} autoComplete="new-password" className="min-h-11 rounded-lg border px-3 py-2 font-normal"/></label><button disabled={busy} className="min-h-11 rounded-lg bg-slate-900 px-4 py-2 font-semibold text-white hover:bg-slate-800 disabled:opacity-50 sm:justify-self-start">{busy ? "Đang cập nhật..." : "Đổi mật khẩu"}</button></form></section></main></div></div>;
}
