"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import AppNav from "@/components/AppNav";
import { useAuth } from "@/lib/auth";

export default function AccountShell({ userLabel, roleName, email, phone, username }: { userLabel: string; roleName: string; email: string | null; phone: string | null; username: string | null }) {
  const router = useRouter(); const { logout } = useAuth();
  const [name, setName] = useState(userLabel); const [emailValue, setEmailValue] = useState(email ?? ""); const [phoneValue, setPhoneValue] = useState(phone ?? "");
  const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const request = async (path: string, body: object) => { setBusy(true); setMessage(""); try { const response = await fetch(path, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json().catch(() => null) as { error?: string; message?: string } | null; if (!response.ok) throw new Error(data?.error ?? "Không thể cập nhật."); setMessage(data?.message ?? "Đã cập nhật."); return true; } catch (error) { setMessage(error instanceof Error ? error.message : "Không thể cập nhật."); return false; } finally { setBusy(false); } };
  const saveProfile = async (event: React.FormEvent) => { event.preventDefault(); await request("/api/account/profile", { fullName: name, email: emailValue, phone: phoneValue }); };
  const changePassword = async (event: React.FormEvent) => { event.preventDefault(); if (newPassword !== confirmPassword) return setMessage("Mật khẩu xác nhận không khớp."); const ok = await request("/api/account/password", { currentPassword, newPassword, confirmPassword }); if (ok) { setCurrentPassword(""); setNewPassword(""); setConfirmPassword(""); setMessage("Đã đổi mật khẩu. Vui lòng đăng nhập lại."); logout(); router.replace("/login"); } };
  return <div className="min-h-screen bg-slate-50 px-3 py-4 text-slate-900"><div className="flex w-full flex-col gap-4 lg:flex-row"><AppNav currentPath="/account" userLabel={userLabel} onLogout={() => { logout(); router.replace("/login"); }} /><main className="min-w-0 flex-1 space-y-4"><section className="rounded-xl border bg-white p-4 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-orange-600">Tài khoản</p><h1 className="mt-2 text-2xl font-bold">Thông tin cá nhân</h1><p className="mt-1 text-sm text-slate-500">Tên đăng nhập: {username ?? "—"} · Vai trò: {roleName}</p>{message ? <p role="status" className="mt-3 rounded bg-slate-50 p-3 text-sm">{message}</p> : null}<form onSubmit={saveProfile} className="mt-4 grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-sm font-semibold">Họ và tên<input value={name} onChange={(e) => setName(e.target.value)} required maxLength={120} className="rounded border px-3 py-2 font-normal" /></label><label className="grid gap-1 text-sm font-semibold">Email<input type="email" value={emailValue} onChange={(e) => setEmailValue(e.target.value)} className="rounded border px-3 py-2 font-normal" /></label><label className="grid gap-1 text-sm font-semibold">Số điện thoại<input value={phoneValue} onChange={(e) => setPhoneValue(e.target.value)} className="rounded border px-3 py-2 font-normal" /></label><div className="flex items-end"><button disabled={busy} className="rounded bg-orange-600 px-4 py-2 font-semibold text-white">Lưu thông tin</button></div></form></section><section className="rounded-xl border bg-white p-4 shadow-sm"><h2 className="text-xl font-bold">Đổi mật khẩu</h2><p className="mt-1 text-sm text-slate-500">Cần nhập mật khẩu hiện tại. Sau khi đổi, các phiên đăng nhập cũ sẽ bị đăng xuất.</p><form onSubmit={changePassword} className="mt-4 grid max-w-xl gap-3"><label className="grid gap-1 text-sm font-semibold">Mật khẩu hiện tại<input type="password" value={currentPassword} onChange={(e) => setCurrentPassword(e.target.value)} required className="rounded border px-3 py-2 font-normal" /></label><label className="grid gap-1 text-sm font-semibold">Mật khẩu mới<input type="password" value={newPassword} onChange={(e) => setNewPassword(e.target.value)} required minLength={8} className="rounded border px-3 py-2 font-normal" /></label><label className="grid gap-1 text-sm font-semibold">Nhập lại mật khẩu mới<input type="password" value={confirmPassword} onChange={(e) => setConfirmPassword(e.target.value)} required minLength={8} className="rounded border px-3 py-2 font-normal" /></label><button disabled={busy} className="rounded bg-slate-900 px-4 py-2 font-semibold text-white sm:justify-self-start">Đổi mật khẩu</button></form></section></main></div></div>;
}
