"use client";
import { useState } from "react";
import { responseErrorMessage } from "@/lib/actionFeedback";

type Review = { result:string; on_time:boolean; issue_notes:string|null; evidence_name:string|null; reviewed_at:string } | null;
export type DutyReviewRow = { id:string; due_date:string; due_time:string|null; duty_position:string; assignee:{full_name:string|null}|null; duty_task_reviews:Review|Review[] };
const normalized = (value: Review | Review[]) => Array.isArray(value) ? value[0] ?? null : value;
export default function DutyReviewCard({ row }: { row:DutyReviewRow }) {
  const existing = normalized(row.duty_task_reviews); const [result,setResult]=useState(existing?.result??"completed"); const [onTime,setOnTime]=useState(existing?.on_time??true); const [notes,setNotes]=useState(existing?.issue_notes??""); const [file,setFile]=useState<File|null>(null); const [evidence,setEvidence]=useState(existing?.evidence_name??null); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  const save=async()=>{setBusy(true);setMessage("");try{const form=new FormData();form.set("taskId",row.id);form.set("result",result);form.set("onTime",String(onTime));form.set("issueNotes",notes);if(file)form.set("evidence",file);const response=await fetch("/api/tasks/duty/review",{method:"POST",body:form});if(!response.ok)throw new Error(await responseErrorMessage(response,"Không thể lưu đánh giá."));if(file)setEvidence(file.name);setFile(null);setMessage("Đã lưu đánh giá.");}catch(error){setMessage(error instanceof Error?error.message:"Không thể lưu đánh giá.");}finally{setBusy(false);}};
  const date=row.due_date.split("-").reverse().join("/");
  return <article className="rounded-xl border border-slate-200 bg-white p-3 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-bold text-slate-900">{date} · {row.duty_position}</p><p className="text-sm text-slate-500">{row.assignee?.full_name??"Chưa có người trực"} · Hạn {row.due_time?.slice(0,5)??"22:00"}</p></div>{existing?<span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-700">Đã đánh giá</span>:<span className="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-bold text-amber-700">Chưa đánh giá</span>}</div><div className="mt-3 grid gap-2 sm:grid-cols-2"><label className="grid gap-1 text-sm font-semibold">Kết quả<select value={result} onChange={e=>setResult(e.target.value)} className="rounded-lg border px-3 py-2 font-normal"><option value="completed">Hoàn thành tốt</option><option value="issues">Hoàn thành, có sai sót</option><option value="not_completed">Không hoàn thành</option></select></label><label className="grid gap-1 text-sm font-semibold">Thời hạn<select value={String(onTime)} onChange={e=>setOnTime(e.target.value==="true")} className="rounded-lg border px-3 py-2 font-normal"><option value="true">Đúng deadline</option><option value="false">Quá deadline</option></select></label><label className="grid gap-1 text-sm font-semibold sm:col-span-2">Sai sót / nhận xét<textarea value={notes} onChange={e=>setNotes(e.target.value)} maxLength={2000} rows={2} placeholder="Ghi rõ sai sót hoặc nhận xét kết quả trực…" className="rounded-lg border px-3 py-2 font-normal"/></label><label className="grid gap-1 text-sm font-semibold sm:col-span-2">File minh chứng<input type="file" accept="image/jpeg,image/png,application/pdf,.docx,.xlsx" onChange={e=>setFile(e.target.files?.[0]??null)} className="rounded-lg border bg-slate-50 px-3 py-2 font-normal"/><span className="text-xs font-normal text-slate-500">Ảnh, PDF, DOCX hoặc XLSX · tối đa 10 MB</span></label></div>{evidence?<a href={`/api/tasks/duty/review?taskId=${row.id}`} target="_blank" rel="noreferrer" className="mt-2 inline-block text-sm font-semibold text-blue-700 hover:underline">Xem minh chứng: {evidence}</a>:null}<div className="mt-3 flex items-center gap-3"><button type="button" disabled={busy} onClick={()=>void save()} className="rounded-lg bg-orange-600 px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{busy?"Đang lưu…":"Lưu đánh giá"}</button>{message?<span role="status" className="text-sm text-slate-600">{message}</span>:null}</div></article>;
}
