"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import AppNav from "@/components/AppNav";
import { useAuth } from "@/lib/auth";
import type { PerformanceCycleHistory } from "@/lib/evaluationRepository";
import { errorMessage, responseErrorMessage } from "@/lib/actionFeedback";
import { useActionFeedback } from "@/components/ActionFeedbackProvider";

export default function EvaluationCycleShell({ userLabel, cycles, failed }: { userLabel: string; cycles: PerformanceCycleHistory[]; failed: boolean }) {
  const router = useRouter(); const { logout } = useAuth(); const { notify } = useActionFeedback(); const [busy, setBusy] = useState(false); const [error, setError] = useState(false); const [cycleMonth, setCycleMonth] = useState(""); const [cycleStatus, setCycleStatus] = useState("");
  const filtered = cycles.filter((cycle) => (!cycleMonth || cycle.start_date.startsWith(cycleMonth)) && (!cycleStatus || cycle.status === cycleStatus));
  const send = async (body: Record<string, unknown>) => { setBusy(true); setError(false); try { const response = await fetch("/api/evaluation-rubrics", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (!response.ok) throw new Error(await responseErrorMessage(response, "Không thể quản trị kỳ đánh giá.")); notify("success", "Đã cập nhật kỳ đánh giá."); router.refresh(); } catch (caught) { setError(true); notify("error", errorMessage(caught, "Không thể quản trị kỳ đánh giá.")); } finally { setBusy(false); } };
  return <div className="min-h-screen bg-slate-50 px-3 py-4 text-slate-900 sm:px-4 lg:px-6"><div className="flex w-full flex-col gap-4 lg:flex-row"><AppNav currentPath="/configuration/evaluation-cycles" userLabel={userLabel} onLogout={() => { logout(); router.replace("/login"); }} /><main className="min-w-0 flex-1"><header className="rounded-xl border bg-white p-4 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-orange-600">Cấu hình</p><h1 className="mt-2 text-2xl font-bold">Quản trị kỳ đánh giá</h1><p className="mt-1 text-sm text-slate-600">Kỳ tuần chạy từ thứ Hai đến Chủ nhật; tuần giao tháng thuộc tháng của ngày thứ Hai.</p></header>
    {failed || error ? <p role="alert" className="mt-4 rounded-lg bg-red-50 p-4 text-red-800">Không thể tải hoặc cập nhật kỳ đánh giá.</p> : null}
    <section className="mt-4 rounded-xl border bg-white p-4 shadow-sm"><div className="flex flex-wrap gap-2"><button disabled={busy} onClick={() => void send({ action: "open_week" })} className="rounded bg-slate-900 px-3 py-2 text-sm font-semibold text-white">Mở kỳ tuần hiện tại</button><button disabled={busy} onClick={() => void send({ action: "open_month" })} className="rounded bg-orange-600 px-3 py-2 text-sm font-semibold text-white">Mở kỳ tháng hiện tại</button></div><details className="mt-3"><summary className="cursor-pointer text-sm font-semibold">Mở kỳ thủ công</summary><form action={(form) => send({ action: "open_cycle", code: form.get("code"), name: form.get("name"), startDate: form.get("startDate"), endDate: form.get("endDate") })} className="mt-3 grid gap-3 md:grid-cols-5"><input required name="code" placeholder="Mã kỳ" className="rounded border px-3 py-2" /><input required name="name" placeholder="Tên kỳ" className="rounded border px-3 py-2" /><input required name="startDate" type="date" className="rounded border px-3 py-2" /><input required name="endDate" type="date" className="rounded border px-3 py-2" /><button disabled={busy} className="rounded border px-3 py-2 font-semibold">Mở kỳ</button></form></details></section>
    <section className="mt-4 rounded-xl border bg-white p-4 shadow-sm"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="font-bold">Danh sách kỳ đánh giá</h2><p className="text-sm text-slate-500">Đã có {cycles.length} kỳ.</p></div><div className="flex gap-2"><input aria-label="Lọc theo tháng" type="month" value={cycleMonth} onChange={(event) => setCycleMonth(event.target.value)} className="rounded border px-3 py-2 text-sm" /><select aria-label="Lọc trạng thái" value={cycleStatus} onChange={(event) => setCycleStatus(event.target.value)} className="rounded border px-3 py-2 text-sm"><option value="">Tất cả trạng thái</option><option value="open">Đang mở</option><option value="closed">Đã đóng</option><option value="draft">Nháp</option></select></div></div>
      <div className="mt-3 overflow-auto"><table className="w-full min-w-[1050px] border-collapse text-sm"><thead><tr className="border-b text-left text-slate-600"><th className="p-2">Mã / tên kỳ</th><th className="p-2">Loại</th><th className="p-2">Khoảng ngày</th><th className="p-2">Trạng thái</th><th className="p-2">Rubric</th><th className="p-2">Tổng hồ sơ</th><th className="p-2">Chờ Trưởng phòng</th><th className="p-2">Chờ Tổng Biên Tập</th><th className="p-2">Đã công bố</th></tr></thead><tbody>{filtered.map((cycle) => <tr key={cycle.id} className="border-b"><td className="p-2"><Link href={`/configuration/evaluation-cycles/${cycle.id}`} className="font-semibold text-orange-700 hover:underline">{cycle.code}</Link><p className="text-slate-500">{cycle.name}</p></td><td className="p-2">{cycle.cycle_type === "weekly" ? "Tuần" : "Tháng"}</td><td className="p-2">{cycle.start_date} – {cycle.end_date}</td><td className="p-2">{cycle.status}</td><td className="p-2">{cycle.rubric_versions}</td><td className="p-2 font-semibold">{cycle.total_reviews}</td><td className="p-2">{cycle.awaiting_manager_count}</td><td className="p-2">{cycle.awaiting_tbt_count}</td><td className="p-2">{cycle.published_count}</td></tr>)}</tbody></table></div>{!filtered.length ? <p className="p-5 text-center text-slate-500">Không có kỳ phù hợp bộ lọc.</p> : null}</section>
  </main></div></div>;
}
