"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import AppNav from "@/components/AppNav";
import { useAuth } from "@/lib/auth";
import type { PerformanceCycleHistory, RubricVersion } from "@/lib/evaluationRepository";
import { errorMessage, responseErrorMessage } from "@/lib/actionFeedback";
import { useActionFeedback } from "@/components/ActionFeedbackProvider";

type Props = { userLabel: string; rubrics: RubricVersion[]; cycles: PerformanceCycleHistory[]; failed: boolean };

export default function EvaluationRubricShell({ userLabel, rubrics, cycles, failed }: Props) {
  const router = useRouter(); const { logout } = useAuth(); const { notify } = useActionFeedback(); const [busy, setBusy] = useState(false); const [error, setError] = useState(false);
  const [cycleMonth, setCycleMonth] = useState(""); const [cycleStatus, setCycleStatus] = useState("");
  const filteredCycles = cycles.filter((cycle) => (!cycleMonth || cycle.start_date.startsWith(cycleMonth)) && (!cycleStatus || cycle.status === cycleStatus));
  const send = async (body: Record<string, unknown>) => { setBusy(true); setError(false); try { const response = await fetch("/api/evaluation-rubrics", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (!response.ok) throw new Error(await responseErrorMessage(response, "Không thể thực hiện thao tác rubric.")); const labels: Record<string,string> = { update: "Đã lưu draft rubric.", publish: "Đã publish rubric.", clone: "Đã clone rubric.", retire: "Đã retire rubric.", open_cycle: "Đã mở kỳ đánh giá.", open_week: "Đã mở kỳ tuần hiện tại.", open_month: "Đã mở kỳ tháng hiện tại." }; notify("success", labels[String(body.action)] || "Đã cập nhật cấu hình."); router.refresh(); } catch (error) { setError(true); notify("error", errorMessage(error, "Không thể thực hiện thao tác rubric.")); } finally { setBusy(false); } };
  const update = (rubric: RubricVersion, form: FormData) => send({ action: "update", rubricId: rubric.id, factors: rubric.evaluation_rubric_factors.map((factor) => ({ ...factor, label: String(form.get(`label-${factor.factor_code}`)), description: String(form.get(`description-${factor.factor_code}`)), max_score: Number(form.get(`max-${factor.factor_code}`)) })) });
  return <div className="min-h-screen bg-slate-50 px-3 py-4 text-slate-900 sm:px-4 lg:px-6"><div className="flex w-full flex-col gap-4 lg:flex-row"><AppNav currentPath="/configuration/evaluation-rubrics" userLabel={userLabel} onLogout={() => { logout(); router.replace("/login"); }} /><main className="min-w-0 flex-1"><header className="rounded-xl border bg-white p-4 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-orange-600">Cấu hình</p><h1 className="mt-2 text-2xl font-bold">Bộ tiêu chí đánh giá chung</h1><p className="mt-1 text-sm text-slate-600">Một rubric dùng toàn cơ quan. Bản đã công bố và snapshot đánh giá không thể sửa.</p></header>
    {failed || error ? <p role="alert" className="mt-4 rounded-lg bg-red-50 p-4 text-red-800">Không thể thực hiện thao tác.</p> : null}
    <section className="mt-4 rounded-xl border bg-white p-4 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold">Quản trị kỳ đánh giá</h2><p className="mt-1 text-sm text-slate-500">Kỳ tuần chạy từ thứ Hai đến Chủ nhật; tuần giao tháng thuộc tháng của ngày thứ Hai bắt đầu tuần.</p></div><div className="flex flex-wrap gap-2"><button type="button" disabled={busy} onClick={() => void send({ action: "open_week" })} className="rounded bg-slate-900 px-3 py-2 text-sm font-semibold text-white">Mở kỳ tuần hiện tại</button><button type="button" disabled={busy} onClick={() => void send({ action: "open_month" })} className="rounded bg-orange-600 px-3 py-2 text-sm font-semibold text-white">Mở kỳ tháng hiện tại</button></div></div><details className="mt-3"><summary className="cursor-pointer text-sm font-semibold text-slate-700">Mở kỳ thủ công</summary><form action={(form) => send({ action: "open_cycle", code: form.get("code"), name: form.get("name"), startDate: form.get("startDate"), endDate: form.get("endDate") })} className="mt-3 grid gap-3 md:grid-cols-5"><input required name="code" placeholder="Mã kỳ" className="rounded border px-3 py-2" /><input required name="name" placeholder="Tên kỳ" className="rounded border px-3 py-2" /><input required name="startDate" type="date" className="rounded border px-3 py-2" /><input required name="endDate" type="date" className="rounded border px-3 py-2" /><button disabled={busy} className="rounded border px-3 py-2 font-semibold">Mở kỳ</button></form></details><p className="mt-2 text-xs text-slate-500">Đã có {cycles.length} kỳ đánh giá.</p></section>
    <section className="mt-4 rounded-xl border bg-white p-4 shadow-sm"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="font-bold">Lịch sử kỳ đánh giá</h2><p className="text-sm text-slate-500">Xem lại rubric và tiến độ chấm của từng kỳ.</p></div><div className="flex flex-wrap gap-2"><label className="grid gap-1 text-xs font-semibold">Tháng<input type="month" value={cycleMonth} onChange={(event) => setCycleMonth(event.target.value)} className="rounded border px-3 py-2 text-sm font-normal" /></label><label className="grid gap-1 text-xs font-semibold">Trạng thái<select value={cycleStatus} onChange={(event) => setCycleStatus(event.target.value)} className="rounded border px-3 py-2 text-sm font-normal"><option value="">Tất cả</option><option value="open">Đang mở</option><option value="closed">Đã đóng</option><option value="draft">Nháp</option></select></label></div></div>
      <div className="mt-3 max-h-[520px] overflow-auto"><table className="w-full min-w-[980px] border-collapse text-sm"><thead><tr className="border-b text-left text-slate-600"><th className="p-2">Mã / tên kỳ</th><th className="p-2">Loại</th><th className="p-2">Khoảng ngày</th><th className="p-2">Trạng thái</th><th className="p-2">Rubric</th><th className="p-2">Tổng hồ sơ</th><th className="p-2">Chờ Trưởng phòng</th><th className="p-2">Chờ TBT</th><th className="p-2">Đã công bố</th><th className="p-2">Xem lại</th></tr></thead><tbody>{filteredCycles.map((cycle) => <tr key={cycle.id} className="border-b align-top"><td className="p-2"><p className="font-semibold">{cycle.code}</p><p className="text-slate-500">{cycle.name}</p></td><td className="p-2">{cycle.cycle_type === "weekly" ? "Tuần" : "Tháng"}</td><td className="p-2">{cycle.cycle_type === "weekly" ? "Tuần" : "Tháng"}</td><td className="p-2">{cycle.cycle_type === "weekly" ? "Tuần" : "Tháng"}</td><td className="p-2">{cycle.start_date} – {cycle.end_date}</td><td className="p-2">{cycle.status}</td><td className="p-2">{cycle.rubric_versions}</td><td className="p-2 font-semibold">{cycle.total_reviews}</td><td className="p-2">{cycle.awaiting_manager_count}</td><td className="p-2">{cycle.awaiting_tbt_count}</td><td className="p-2">{cycle.published_count}</td><td className="p-2"><details><summary className="cursor-pointer font-semibold text-orange-700">Chi tiết</summary><div className="mt-2 whitespace-nowrap text-xs text-slate-600"><p>Self draft/legacy: {cycle.self_draft_count}</p><p>Trạng thái khác: {cycle.other_count}</p><p>Rubric snapshot: {cycle.rubric_versions}</p></div></details></td></tr>)}</tbody></table></div>
      {!filteredCycles.length ? <p className="p-5 text-center text-slate-500">Không có kỳ đánh giá phù hợp bộ lọc.</p> : null}
    </section>
    <section className="mt-4 space-y-4">{rubrics.map((rubric) => <article key={rubric.id} className="rounded-xl border bg-white p-4 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-bold">Phiên bản {rubric.version_no}</h2><span className="rounded-full bg-slate-100 px-3 py-1 text-sm">{rubric.status}</span></div><p className="mt-1 text-sm text-slate-500">Hiệu lực: {rubric.effective_from ?? "Chưa đặt"}</p>
      <form action={(form) => update(rubric, form)} className="mt-3 space-y-3">{rubric.evaluation_rubric_factors.sort((a,b) => a.position-b.position).map((factor) => <fieldset disabled={rubric.status !== "draft"} key={factor.factor_code} className="grid gap-2 rounded-lg border p-3 md:grid-cols-[110px_minmax(0,1fr)_100px]"><legend className="px-1 text-xs font-semibold">{factor.factor_code}</legend><input name={`label-${factor.factor_code}`} defaultValue={factor.label} className="rounded border px-2 py-1 md:col-span-2" /><input name={`max-${factor.factor_code}`} type="number" min="1" defaultValue={factor.max_score} className="rounded border px-2 py-1" /><textarea name={`description-${factor.factor_code}`} defaultValue={factor.description} className="rounded border px-2 py-1 md:col-span-3" /></fieldset>)}{rubric.status === "draft" ? <div className="flex flex-wrap gap-2"><button disabled={busy} className="rounded bg-slate-900 px-3 py-2 text-sm font-semibold text-white">Lưu draft</button><input required name="effectiveFrom" type="date" className="rounded border px-2 py-1" /><button type="button" disabled={busy} onClick={(event) => { const form = event.currentTarget.form; const date = form ? new FormData(form).get("effectiveFrom") : null; void send({ action: "publish", rubricId: rubric.id, effectiveFrom: date }); }} className="rounded bg-orange-500 px-3 py-2 text-sm font-semibold text-white">Publish</button></div> : null}</form>
      {rubric.status === "published" ? <div className="mt-3 flex gap-2"><button disabled={busy} onClick={() => send({ action: "clone", rubricId: rubric.id })} className="rounded bg-orange-500 px-3 py-2 text-sm font-semibold text-white">Clone thành draft mới</button><button disabled={busy} onClick={() => send({ action: "retire", rubricId: rubric.id })} className="rounded border px-3 py-2 text-sm font-semibold">Retire</button></div> : null}</article>)}</section>
  </main></div></div>;
}
