"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import AppNav from "@/components/AppNav";
import { useAuth } from "@/lib/auth";
import type { RubricVersion } from "@/lib/evaluationRepository";
import { errorMessage, responseErrorMessage } from "@/lib/actionFeedback";
import { useActionFeedback } from "@/components/ActionFeedbackProvider";

const rubricStatusLabel:Record<string,string>={draft:"Bản nháp",published:"Đã công bố",retired:"Ngừng sử dụng"};
export default function EvaluationRubricShell({ userLabel, rubrics, failed }: { userLabel: string; rubrics: RubricVersion[]; failed: boolean }) {
  const router = useRouter(); const { logout } = useAuth(); const { notify } = useActionFeedback(); const [busy, setBusy] = useState(false); const [error, setError] = useState(false);
  const send = async (body: Record<string, unknown>) => { setBusy(true); setError(false); try { const response = await fetch("/api/evaluation-rubrics", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (!response.ok) throw new Error(await responseErrorMessage(response, "Không thể thực hiện thao tác rubric.")); const labels: Record<string,string> = { update: "Đã lưu draft rubric.", publish: "Đã publish rubric.", clone: "Đã clone rubric.", retire: "Đã retire rubric." }; notify("success", labels[String(body.action)] || "Đã cập nhật cấu hình."); router.refresh(); } catch (caught) { setError(true); notify("error", errorMessage(caught, "Không thể thực hiện thao tác rubric.")); } finally { setBusy(false); } };
  const update = (rubric: RubricVersion, form: FormData) => send({ action: "update", rubricId: rubric.id, factors: rubric.evaluation_rubric_factors.map((factor) => ({ ...factor, label: String(form.get(`label-${factor.factor_code}`)), description: String(form.get(`description-${factor.factor_code}`)), max_score: Number(form.get(`max-${factor.factor_code}`)) })) });
  return <div className="min-h-screen bg-slate-50 px-3 py-4 text-slate-900 sm:px-4 lg:px-6"><div className="flex w-full flex-col gap-4 lg:flex-row"><AppNav currentPath="/configuration/evaluation-rubrics" userLabel={userLabel} onLogout={() => { logout(); router.replace("/login"); }} /><main className="min-w-0 flex-1"><header className="rounded-xl border bg-white p-4 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-orange-600">Cấu hình</p><h1 className="mt-2 text-2xl font-bold">Bộ tiêu chí đánh giá chung</h1><p className="mt-1 text-sm text-slate-600">Một rubric dùng toàn cơ quan. Bản đã công bố và snapshot đánh giá không thể sửa.</p></header>
    {failed || error ? <p role="alert" className="mt-4 rounded-lg bg-red-50 p-4 text-red-800">Không thể thực hiện thao tác.</p> : null}
    <section className="mt-4 space-y-4">{rubrics.map((rubric) => <article key={rubric.id} className="rounded-xl border bg-white p-4 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-bold">Phiên bản {rubric.version_no}</h2><span className="rounded-full bg-slate-100 px-3 py-1 text-sm">{rubricStatusLabel[rubric.status]??rubric.status}</span></div><p className="mt-1 text-sm text-slate-500">Hiệu lực: {rubric.effective_from ?? "Chưa đặt"}</p>
      <form action={(form) => update(rubric, form)} className="mt-3 space-y-3">{rubric.evaluation_rubric_factors.sort((a,b) => a.position-b.position).map((factor) => <fieldset disabled={rubric.status !== "draft"} key={factor.factor_code} className="grid gap-2 rounded-lg border p-3 md:grid-cols-[110px_minmax(0,1fr)_100px]"><legend className="px-1 text-xs font-semibold">{factor.factor_code}</legend><input name={`label-${factor.factor_code}`} defaultValue={factor.label} className="rounded border px-2 py-1 md:col-span-2" /><input name={`max-${factor.factor_code}`} type="number" min="1" defaultValue={factor.max_score} className="rounded border px-2 py-1" /><textarea name={`description-${factor.factor_code}`} defaultValue={factor.description} className="rounded border px-2 py-1 md:col-span-3" /></fieldset>)}{rubric.status === "draft" ? <div className="flex flex-wrap gap-2"><button disabled={busy} className="rounded bg-slate-900 px-3 py-2 text-sm font-semibold text-white">Lưu bản nháp</button><input required name="effectiveFrom" type="date" className="rounded border px-2 py-1" /><button type="button" disabled={busy} onClick={(event) => { const form = event.currentTarget.form; const date = form ? new FormData(form).get("effectiveFrom") : null; void send({ action: "publish", rubricId: rubric.id, effectiveFrom: date }); }} className="rounded bg-orange-500 px-3 py-2 text-sm font-semibold text-white">Công bố</button></div> : null}</form>
      {rubric.status === "published" ? <div className="mt-3 flex gap-2"><button disabled={busy} onClick={() => send({ action: "clone", rubricId: rubric.id })} className="rounded bg-orange-500 px-3 py-2 text-sm font-semibold text-white">Tạo bản nháp mới</button><button disabled={busy} onClick={() => send({ action: "retire", rubricId: rubric.id })} className="rounded border px-3 py-2 text-sm font-semibold">Ngừng sử dụng</button></div> : null}</article>)}</section>
  </main></div></div>;
}
