"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import AppNav from "@/components/AppNav";
import { useAuth } from "@/lib/auth";
import type { EvaluationCycleDetail } from "@/lib/evaluationRepository";

const statusLabel: Record<string,string> = { self_draft: "Chưa bắt đầu", awaiting_manager: "Chờ Trưởng phòng", awaiting_tbt: "Chờ Tổng Biên Tập", published: "Đã công bố" };
const scoreFor = (review: EvaluationCycleDetail["reviews"][number], stage: "self" | "manager" | "tbt", factorCode: string) => review.scores.find((score) => score.stage === stage && score.factorCode === factorCode);
const total = (review: EvaluationCycleDetail["reviews"][number], stage: "self" | "manager" | "tbt") => review.scores.filter((score) => score.stage === stage).reduce((sum, score) => sum + score.score, 0);

export default function EvaluationCycleDetailShell({ userLabel, cycle }: { userLabel: string; cycle: EvaluationCycleDetail }) {
  const router = useRouter(); const { logout } = useAuth();
  return <div className="min-h-screen bg-slate-50 px-3 py-4 text-slate-900 sm:px-4 lg:px-6"><div className="flex w-full flex-col gap-4 lg:flex-row"><AppNav currentPath="/configuration/evaluation-cycles" userLabel={userLabel} onLogout={() => { logout(); router.replace("/login"); }} /><main className="min-w-0 flex-1"><header className="rounded-xl border bg-white p-4 shadow-sm"><Link href="/configuration/evaluation-cycles" className="text-sm font-semibold text-orange-700 hover:underline">← Quản trị kỳ đánh giá</Link><div className="mt-3 flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-orange-600">{cycle.cycleType === "weekly" ? "Kỳ tuần" : "Kỳ tháng"}</p><h1 className="mt-1 text-2xl font-bold">{cycle.name}</h1><p className="mt-1 text-sm text-slate-600">{cycle.code} · {cycle.startDate} – {cycle.endDate}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-sm font-semibold">{cycle.status}</span></div></header>
    <section className="mt-4 rounded-xl border bg-white p-4 shadow-sm"><div className="grid gap-3 sm:grid-cols-4"><Stat label="Tổng hồ sơ" value={cycle.reviews.length} /><Stat label="Chờ Trưởng phòng" value={cycle.reviews.filter((row) => row.status === "awaiting_manager").length} /><Stat label="Chờ Tổng Biên Tập" value={cycle.reviews.filter((row) => row.status === "awaiting_tbt").length} /><Stat label="Đã công bố" value={cycle.reviews.filter((row) => row.status === "published").length} /></div></section>
    <section className="mt-4 space-y-3">{cycle.reviews.map((review) => <details key={review.id} className="rounded-xl border bg-white shadow-sm"><summary className="cursor-pointer list-none p-4 [&::-webkit-details-marker]:hidden"><div className="grid items-center gap-2 sm:grid-cols-[minmax(180px,1.4fr)_minmax(140px,1fr)_150px_110px_110px]"><div><p className="font-bold">{review.employeeName}</p><p className="text-xs text-slate-500">{review.workflowType === "manager" ? "Trưởng/Phó phòng" : "Nhân viên"}</p></div><p className="text-sm">{review.departmentName}</p><span className="text-sm font-semibold">{statusLabel[review.status] ?? review.status}</span><p className="text-sm"><b>TP:</b> {review.managerScore ?? "—"}</p><p className="text-sm"><b>Cuối:</b> {review.finalScore ?? "—"}</p></div></summary><div className="border-t p-4"><div className="overflow-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr className="border-b text-left text-slate-500"><th className="p-2">Tiêu chí</th><th className="p-2">Tối đa</th><th className="p-2">Tự đánh giá</th><th className="p-2">Trưởng phòng</th><th className="p-2">Tổng Biên Tập</th></tr></thead><tbody>{review.factors.sort((a,b) => a.position-b.position).map((factor) => <tr key={factor.factor_code} className="border-b align-top"><td className="p-2"><p className="font-semibold">{factor.label}</p><p className="text-xs text-slate-500">{factor.factor_code}</p></td><td className="p-2">{factor.max_score}</td>{(["self","manager","tbt"] as const).map((stage) => { const score = scoreFor(review, stage, factor.factor_code); return <td key={stage} className="p-2"><p className="font-semibold">{score?.score ?? "—"}</p>{score?.comment ? <p className="mt-1 whitespace-pre-wrap text-xs text-slate-500">{score.comment}</p> : null}</td>; })}</tr>)}</tbody><tfoot><tr className="font-bold"><td className="p-2">Tổng điểm</td><td className="p-2">{review.factors.reduce((sum,factor) => sum + factor.max_score, 0)}</td>{(["self","manager","tbt"] as const).map((stage) => <td key={stage} className="p-2">{review.scores.some((score) => score.stage === stage) ? total(review, stage) : "—"}</td>)}</tr></tfoot></table></div><p className="mt-3 text-sm"><b>Xếp loại:</b> {review.rank ?? "Chưa xếp loại"}</p></div></details>)}{!cycle.reviews.length ? <p className="rounded-xl border bg-white p-6 text-center text-slate-500">Kỳ này chưa có hồ sơ đánh giá.</p> : null}</section>
  </main></div></div>;
}
function Stat({ label, value }: { label: string; value: number }) { return <div className="rounded-lg bg-slate-50 p-3"><p className="text-xs font-semibold uppercase text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></div>; }
