"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import { errorMessage, responseErrorMessage } from "@/lib/actionFeedback";
import { useActionFeedback } from "@/components/ActionFeedbackProvider";
import type { JournalismTaskDetailDto } from "@/lib/taskContracts";
import type { JournalismStructureSeries, JournalismStructureTopic } from "@/lib/journalismStructureRepository";
import { journalismLabels } from "@/lib/journalismUi.mjs";

export default function JournalismAssociationControls({ taskId, journalism, topics, series, canAssign }: { taskId: string; journalism: JournalismTaskDetailDto; topics: JournalismStructureTopic[]; series: JournalismStructureSeries[]; canAssign: boolean }) {
  const router = useRouter(); const { notify } = useActionFeedback(); const [busy, setBusy] = useState(false); const [topicId, setTopicId] = useState(""); const [seriesId, setSeriesId] = useState("");
  if (!canAssign) return null;
  const attachedTopicIds = new Set(journalism.topics.map((topic) => topic.id));
  const availableTopics = topics.filter((topic) => !attachedTopicIds.has(topic.id));
  const availableSeries = series.filter((item) => !journalism.series || item.id !== journalism.series.id);
  const request = async (path: string, init: RequestInit) => { setBusy(true); try { const response = await fetch(path, init); if (response.status === 403) throw new Error("Bạn không có quyền thực hiện thao tác này."); if (response.status === 409) { notify("error", "Dữ liệu liên kết đã thay đổi. Dữ liệu mới nhất đã được tải lại."); router.refresh(); return; } if (!response.ok) throw new Error(await responseErrorMessage(response, "Không thể cập nhật liên kết.")); notify("success", "Đã cập nhật liên kết."); router.refresh(); } catch (error) { notify("error", errorMessage(error, "Không thể cập nhật liên kết.")); } finally { setBusy(false); } };
  return <section aria-label={`Gắn ${journalismLabels.topic.toLowerCase()} và ${journalismLabels.series.toLowerCase()}`} className="rounded-xl border bg-white p-3.5 shadow-sm"><h2 className="mb-3 text-base font-bold sm:text-lg">Cấu trúc biên tập</h2><div className="space-y-3"><div><h3 className="text-sm font-semibold">{journalismLabels.topic}</h3><div className="mt-2 flex flex-wrap gap-2">{journalism.topics.map((topic) => <span key={topic.id} className="inline-flex items-center gap-2 rounded-full bg-orange-100 px-3 py-1.5 text-sm">{topic.name}{topic.isActive ? "" : " (Ngừng sử dụng)"}<button type="button" disabled={busy} onClick={() => request(`/api/tasks/${taskId}/journalism/topics/${topic.id}`, { method: "DELETE" })} className="font-bold text-orange-900 underline">Bỏ khỏi công việc</button></span>)}</div><div className="mt-2 flex flex-col gap-2 sm:flex-row"><select aria-label="Chọn chủ đề" value={topicId} onChange={(event) => setTopicId(event.target.value)} className="min-w-0 flex-1 rounded-lg border px-3 py-2"><option value="">Chọn chủ đề đang hoạt động</option>{availableTopics.map((topic) => <option key={topic.id} value={topic.id}>{topic.name}</option>)}</select><button type="button" disabled={busy || !topicId} onClick={() => { const selected = topicId; setTopicId(""); void request(`/api/tasks/${taskId}/journalism/topics`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ topicId: selected }) }); }} className="rounded-lg bg-orange-600 px-4 py-2 font-semibold text-white disabled:opacity-50">Thêm chủ đề</button></div></div><div><h3 className="text-sm font-semibold">{journalismLabels.series}</h3>{journalism.series ? <div className="mt-2 flex flex-wrap items-center gap-2"><span className="rounded-full bg-amber-100 px-3 py-1.5 text-sm">{journalism.series.name}{journalism.series.isActive ? "" : " (Ngừng sử dụng)"}</span><button type="button" disabled={busy} onClick={() => request(`/api/tasks/${taskId}/journalism/series`, { method: "DELETE" })} className="rounded-lg border px-3 py-2 text-sm font-semibold">Bỏ khỏi loạt bài</button></div> : <div className="mt-2 flex flex-col gap-2 sm:flex-row"><select aria-label="Chọn loạt bài" value={seriesId} onChange={(event) => setSeriesId(event.target.value)} className="min-w-0 flex-1 rounded-lg border px-3 py-2"><option value="">Chọn loạt bài đang hoạt động</option>{availableSeries.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button type="button" disabled={busy || !seriesId} onClick={() => { const selected = seriesId; setSeriesId(""); void request(`/api/tasks/${taskId}/journalism/series`, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ seriesId: selected }) }); }} className="rounded-lg bg-orange-600 px-4 py-2 font-semibold text-white disabled:opacity-50">Thêm vào loạt bài</button></div>}</div></div></section>;
}
