"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import AppNav from "@/components/AppNav";
import { useAuth } from "@/lib/auth";
import { useActionFeedback } from "@/components/ActionFeedbackProvider";
import { errorMessage, responseErrorMessage } from "@/lib/actionFeedback";

type Person={id:string;username:string;full_name:string}; type Day={date:string;staffId:string};
const monthDays=(month:string):Day[]=>{const [y,m]=month.split("-").map(Number);const last=new Date(Date.UTC(y,m,0)).getUTCDate();return Array.from({length:last},(_,i)=>({date:`${month}-${String(i+1).padStart(2,"0")}`,staffId:""}));};
export default function OnlineWorkAdminShell({userLabel,people}:{userLabel:string;people:Person[]}){
 const router=useRouter();const {logout}=useAuth();const {notify}=useActionFeedback();const [month,setMonth]=useState(new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Ho_Chi_Minh",year:"numeric",month:"2-digit"}).format(new Date()).slice(0,7));const [days,setDays]=useState<Day[]>([]);const [base,setBase]=useState("");const [busy,setBusy]=useState(false);
 useEffect(()=>{const next=monthDays(month);setDays(next);setBase(JSON.stringify(next));fetch(`/api/online-work?month=${month}`).then(r=>r.ok?r.json():Promise.reject()).then(body=>{for(const row of body.rows??[]){const d=next.find(x=>x.date===row.work_date);if(d)d.staffId=row.staff_id;}setDays(next);setBase(JSON.stringify(next));}).catch(()=>notify("error","Không tải được lịch online."));},[month,notify]);
 const dirty=JSON.stringify(days)!==base;const update=(date:string,staffId:string)=>setDays(curr=>curr.map(d=>d.date===date?{...d,staffId}:d));const save=async()=>{setBusy(true);try{const res=await fetch("/api/online-work",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({month,days:days.filter(d=>d.staffId)})});if(!res.ok)throw new Error(await responseErrorMessage(res,"Không thể lưu lịch online."));setBase(JSON.stringify(days));notify("success","Đã lưu lịch làm online.");router.refresh();}catch(e){notify("error",errorMessage(e,"Không thể lưu lịch online."));}finally{setBusy(false);}};
 return <div className="min-h-screen bg-slate-50 px-3 py-4 text-slate-900 sm:px-4 lg:px-6"><div className="flex w-full flex-col gap-4 lg:flex-row"><AppNav currentPath="/configuration/online-work" userLabel={userLabel} onLogout={()=>{logout();router.replace("/login");}}/><main className="min-w-0 flex-1"><header className="rounded-xl border bg-white p-4 shadow-sm"><h1 className="text-2xl font-bold">LỊCH LÀM ONLINE (NGOẠI NGỮ)</h1><p className="mt-1 text-sm text-slate-600">Mỗi ngày chọn tối đa một phóng viên làm online.</p></header><section className="mt-4 rounded-xl border bg-white p-4 shadow-sm"><label className="grid max-w-xs gap-1 text-sm font-semibold">Tháng làm online<input type="month" value={month} onChange={e=>setMonth(e.target.value)} className="rounded border px-3 py-2"/></label><div className="mt-4 grid min-w-0 gap-2 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{days.map(day=><label key={day.date} className="grid min-w-0 gap-1 overflow-hidden rounded border p-2 text-sm"><span className="truncate font-semibold" title={day.date}>{day.date}</span><select value={day.staffId} onChange={e=>update(day.date,e.target.value)} className="w-full min-w-0 max-w-full truncate rounded border px-2 py-2"><option value="">Không làm online</option>{people.map(p=><option key={p.id} value={p.id}>{p.username} ({p.full_name})</option>)}</select></label>)}</div><div className="mt-4 flex gap-2"><button disabled={!dirty||busy} onClick={()=>void save()} className="rounded bg-orange-600 px-4 py-2 font-semibold text-white disabled:opacity-50">{busy?"Đang lưu…":"Lưu lịch online"}</button><button disabled={!dirty} onClick={()=>setDays(JSON.parse(base) as Day[])} className="rounded border px-4 py-2 disabled:opacity-50">Hoàn tác</button></div></section></main></div></div>;
}
