"use client";
import { Fragment, useEffect, useState } from "react";
type Task={id:string;title:string;status:string;dueDate:string|null;score:number|null}; type Row={id:string;name:string;department:string;total:number;done:number;overdue:number;score:number|null;tasks:Task[]};
const statusLabel=(s:string)=>({todo:"Chưa bắt đầu",in_progress:"Đang thực hiện",pending_review:"Chờ duyệt",done:"Hoàn thành",completed:"Hoàn thành"}[s]??s);
const dateLabel=(s:string|null)=>s?new Intl.DateTimeFormat("vi-VN",{day:"2-digit",month:"2-digit",year:"2-digit"}).format(new Date(`${s}T00:00:00`)):"—";
export default function PublicEvaluationSummary(){
  const [rows,setRows]=useState<Row[]>([]);
  const [open,setOpen]=useState<string|null>(null);
  useEffect(()=>{fetch("/api/public-evaluation-summary").then(r=>r.json()).then(d=>setRows(d.rows??[]));},[]);
  return <main className="min-h-screen bg-slate-50 p-4"><div className="mx-auto max-w-6xl rounded-2xl border bg-white p-5 shadow-sm"><h1 className="text-2xl font-bold">TỔNG HỢP ĐÁNH GIÁ NHÂN VIÊN</h1><p className="mt-1 text-sm text-slate-600">Bảng công khai cho toàn cơ quan. Chọn một nhân viên để xem các công việc.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[800px] border-collapse text-sm"><thead><tr className="border-b bg-slate-100 text-left"><th className="p-2">STT</th><th className="p-2">Tên nhân viên</th><th className="p-2">Tổng số việc</th><th className="p-2">Hoàn thành</th><th className="p-2">Quá hạn</th><th className="p-2">Tổng điểm</th></tr></thead><tbody>{rows.map((r,i)=><Fragment key={r.id}><tr onClick={()=>setOpen(open===r.id?null:r.id)} className="cursor-pointer border-b hover:bg-orange-50"><td className="p-2">{i+1}</td><td className="p-2 font-semibold">{r.name}<span className="block text-xs font-normal text-slate-500">{r.department}</span></td><td className="p-2 text-center">{r.total}</td><td className="p-2 text-center">{r.done}</td><td className="p-2 text-center">{r.overdue}</td><td className="p-2 text-center font-semibold">{r.score??"—"}</td></tr>{open===r.id&&<tr className="border-b bg-orange-50/50"><td colSpan={6} className="p-3"><div className="rounded-lg border bg-white"><div className="grid grid-cols-[1fr_130px_120px_90px] gap-2 border-b bg-slate-50 px-3 py-2 text-xs font-semibold text-slate-600"><span>Công việc</span><span>Trạng thái</span><span>Hạn hoàn thành</span><span>Điểm</span></div>{r.tasks.length?r.tasks.map(t=><div key={t.id} className="grid grid-cols-[1fr_130px_120px_90px] gap-2 px-3 py-2 text-xs"><span className="font-medium">{t.title}</span><span>{statusLabel(t.status)}</span><span>{dateLabel(t.dueDate)}</span><span>{t.score!=null?t.score:(t.status==="pending_review"?<a href={`/tasks/${t.id}#task-scoring-form`} onClick={e=>e.stopPropagation()} className="font-semibold text-orange-700 underline">Chấm điểm</a>:"—")}</span></div>):<p className="p-3 text-sm text-slate-500">Chưa có công việc.</p>}</div></td></tr>}</Fragment>)}</tbody></table>{!rows.length&&<p className="p-6 text-center text-slate-500">Chưa có dữ liệu nhân viên.</p>}</div></div></main>;
}
