"use client";
import { useState } from "react";
type Person = { id: string; full_name: string; roles?: { code?: string } | null; job_titles?: { code?: string } | null };
export default function WorkScheduleAdminShell({ people, userLabel }: { people: Person[]; userLabel: string }) {
 const [selectedIds,setSelectedIds]=useState<string[]>([]);
 const leaders=people.filter(p=>["tong_bien_tap","pho_tong_bien_tap"].includes(p.roles?.code ?? "") || (p.job_titles?.code ?? "").startsWith("truong_phong"));
 const reporters=people.filter(p=>(p.job_titles?.code ?? "").startsWith("phong_vien") || p.roles?.code === "phong_vien");
 const toggle=(id:string)=>setSelectedIds(ids=>ids.includes(id)?ids.filter(x=>x!==id):[...ids,id]);
 const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
 const save=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);const res=await fetch("/api/work-schedule",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({workDate:f.get("workDate"),startTime:f.get("startTime")||null,endTime:f.get("endTime")||null,title:f.get("title"),location:f.get("location"),notes:f.get("notes"),participantIds:selectedIds})});setMessage(res.ok?"Đã lưu lịch công tác.":"Không thể lưu lịch công tác.");setBusy(false);if(res.ok){e.currentTarget.reset();setSelectedIds([]);}};
 const checkboxList=(items:Person[])=>items.length?<div className="grid gap-2">{items.map(p=><label key={p.id} className="flex items-center gap-2 rounded border border-slate-200 px-2 py-1.5 font-normal"><input type="checkbox" name="participantIds" value={p.id} checked={selectedIds.includes(p.id)} onChange={()=>toggle(p.id)} />{p.full_name}</label>)}</div>:<p className="text-sm font-normal text-slate-500">Chưa có dữ liệu</p>;
 return <main className="min-h-screen bg-slate-50 p-4 text-slate-900"><div className="mx-auto max-w-3xl"><h1 className="text-2xl font-bold">QUẢN TRỊ LỊCH CÔNG TÁC</h1><p className="mt-1 text-sm text-slate-600">Tài khoản: {userLabel}</p><form onSubmit={save} className="mt-4 grid gap-3 rounded-xl border bg-white p-4 shadow-sm"><label className="grid gap-1 text-sm font-semibold">Nội dung công tác<input name="title" required maxLength={500} className="rounded border p-2 font-normal" /></label><div className="grid gap-3 sm:grid-cols-3"><label className="grid gap-1 text-sm font-semibold">Ngày<input name="workDate" type="date" required className="rounded border p-2 font-normal" /></label><label className="grid gap-1 text-sm font-semibold">Bắt đầu<input name="startTime" type="time" className="rounded border p-2 font-normal" /></label><label className="grid gap-1 text-sm font-semibold">Kết thúc<input name="endTime" type="time" className="rounded border p-2 font-normal" /></label></div><label className="grid gap-1 text-sm font-semibold">Địa điểm<input name="location" maxLength={500} className="rounded border p-2 font-normal" /></label><fieldset className="grid gap-2 text-sm font-semibold"><legend>Người đăng ký</legend><div className="grid gap-4 sm:grid-cols-2"><div><h3 className="mb-2 font-semibold text-slate-700">Lãnh đạo</h3>{checkboxList(leaders)}</div><div><h3 className="mb-2 font-semibold text-slate-700">Phóng viên</h3>{checkboxList(reporters)}</div></div></fieldset><label className="grid gap-1 text-sm font-semibold">Ghi chú<textarea name="notes" maxLength={2000} className="rounded border p-2 font-normal" /></label><button disabled={busy} className="rounded bg-orange-600 px-4 py-2 font-semibold text-white">{busy?"Đang lưu…":"Lưu lịch công tác"}</button>{message?<p role="status" className="text-sm">{message}</p>:null}</form></div></main>;
}
