/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import type { WorkReportRow } from "@/lib/workReport";

type FilterChange = Record<string, string | number | null | undefined>;
const sourceOptions = [["", "Tất cả"], ["assigned", "Được giao"], ["department_plan", "Kế hoạch phòng"], ["report_only", "Việc phát sinh"]] as const;
const statusOptions = [["", "Tất cả"], ["done", "Hoàn thành"], ["in_progress", "Đang thực hiện"], ["pending_review", "Chờ duyệt"], ["rejected", "Trả lại"], ["new", "Mới"], ["blocked", "Có vướng mắc"], ["waiting", "Đang chờ"], ["nearly_done", "Sắp xong"]] as const;

export default function WorkReportPage({ initial }: { initial: any }) {
  const router = useRouter();
  const [selected, setSelected] = useState<WorkReportRow | null>(null);
  const navigate = (changes: FilterChange = {}) => {
    const values: Record<string, string | number | null | undefined> = { period: initial.period, from: initial.from, to: initial.to, departmentId: initial.departmentId, employeeId: initial.employeeId, source: initial.source, status: initial.status, page: initial.report.page, pageSize: initial.report.pageSize, ...changes };
    const query = new URLSearchParams();
    for (const [key, value] of Object.entries(values)) if (value !== undefined && value !== null && value !== "" && !(key === "page" && Number(value) === 1)) query.set(key, String(value));
    router.push(`/reports/work?${query.toString()}`);
  };
  const page = Number(initial.report.page) || 1;
  const pageSize = Number(initial.report.pageSize) || 20;
  const total = Number(initial.report.total) || 0;
  const hasPrevious = page > 1;
  const hasNext = page * pageSize < total;
  return <main className="min-h-screen bg-[#f4f1ea] p-4 text-slate-900 sm:p-8"><div className="mx-auto max-w-7xl"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-orange-700">Báo cáo công việc</p><h1 className="text-3xl font-black">Báo cáo công việc</h1><p className="mt-1 text-sm text-slate-600">{initial.from} → {initial.to}</p></div>
    <section className="mt-5 grid gap-3 rounded-2xl border bg-white p-4 shadow-sm sm:grid-cols-2"><label className="grid gap-1 text-sm font-semibold" htmlFor="work-report-source">Nguồn công việc<select id="work-report-source" value={initial.source ?? ""} onChange={(event) => navigate({ source: event.target.value, page: 1 })} className="rounded-lg border px-3 py-2 font-normal">{sourceOptions.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="grid gap-1 text-sm font-semibold" htmlFor="work-report-status">Trạng thái<select id="work-report-status" value={initial.status ?? ""} onChange={(event) => navigate({ status: event.target.value, page: 1 })} className="rounded-lg border px-3 py-2 font-normal">{statusOptions.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></section>
    <section className="mt-5 overflow-x-auto rounded-2xl border bg-white shadow-sm"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-3">Nhân viên</th><th className="p-3">Tổng</th><th className="p-3">Hoàn thành</th><th className="p-3">Đang làm</th><th className="p-3">Việc phát sinh</th></tr></thead><tbody>{initial.report.employees.map((employee: any) => <tr key={employee.id} className="border-t"><td className="p-3 font-semibold"><button type="button" onClick={() => navigate({ employeeId: employee.id, page: 1 })} className="underline decoration-orange-300 underline-offset-2">{employee.full_name}</button></td><td className="p-3">{employee.total}</td><td className="p-3">{employee.completed}</td><td className="p-3">{employee.active}</td><td className="p-3">{employee.reportOnly}</td></tr>)}</tbody></table>{initial.report.employees.length === 0 ? <p className="p-6 text-sm text-slate-500">Không có nhân viên trong phạm vi báo cáo</p> : null}</section>
    <section className="mt-5 overflow-x-auto rounded-2xl border bg-white shadow-sm"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-3">Công việc</th><th className="p-3">Nguồn</th><th className="p-3">Nhân viên</th><th className="p-3">Bắt đầu</th><th className="p-3">Trạng thái</th></tr></thead><tbody>{initial.report.rows.map((row: WorkReportRow) => <tr key={`${row.id}-${row.assigneeId}`} tabIndex={0} onClick={() => setSelected(row)} onKeyDown={(event) => event.key === "Enter" && setSelected(row)} className="cursor-pointer border-t hover:bg-orange-50"><td className="p-3 font-semibold">{row.title}</td><td className="p-3">{row.sourceLabel}</td><td className="p-3">{row.assigneeName ?? "—"}</td><td className="p-3">{row.startDate ?? "—"}</td><td className="p-3">{row.status}</td></tr>)}</tbody></table>{initial.report.rows.length === 0 ? <p className="p-6 text-sm text-slate-500">Không có công việc trong kỳ đã chọn</p> : null}{(hasPrevious || hasNext) ? <nav aria-label="Phân trang báo cáo công việc" className="flex items-center justify-between border-t p-4 text-sm"><button type="button" disabled={!hasPrevious} onClick={() => navigate({ page: page - 1 })} className="rounded border px-3 py-2 disabled:opacity-40">Trang trước</button><span>Trang {page} · {total} công việc</span><button type="button" disabled={!hasNext} onClick={() => navigate({ page: page + 1 })} className="rounded border px-3 py-2 disabled:opacity-40">Trang sau</button></nav> : null}</section></div>
    {selected ? <div role="presentation" onMouseDown={(event) => event.target === event.currentTarget && setSelected(null)} className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><section role="dialog" aria-modal="true" className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-5 shadow-2xl"><div className="flex justify-between gap-4"><div><p className="text-xs font-bold uppercase text-orange-600">Chi tiết công việc</p><h2 className="mt-1 text-xl font-bold">{selected.title}</h2></div><button type="button" onClick={() => setSelected(null)} className="rounded border px-3 py-1">Đóng</button></div><dl className="mt-5 grid gap-3 text-sm sm:grid-cols-2">{[["Nguồn", selected.sourceLabel],["Người thực hiện", selected.assigneeName],["Phòng ban", selected.departmentName],["Ngày bắt đầu", selected.startDate],["Hạn hoàn thành", selected.dueDate],["Ngày hoàn thành", selected.completedAt],["Trạng thái", selected.status],["Nội dung", selected.description],["Kết quả / ghi chú", selected.reportNotes]].filter(([, value]) => value).map(([label, value]) => <div key={label}><dt className="font-bold text-slate-500">{label}</dt><dd className="whitespace-pre-wrap">{value}</dd></div>)}</dl><a href={`/tasks/${selected.id}`} className="mt-5 inline-flex rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Xem công việc đầy đủ</a></section></div> : null}</main>;
}
