"use client";
import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import AppNav from "@/components/AppNav";
import { useAuth } from "@/lib/auth";
import { listPendingAssetStatusRequests, reviewAssetStatusRequest, type AssetStatusChangeRequest } from "@/lib/services";

export default function AssetStatusRequestsPage() {
  const router = useRouter(); const { loading, user, logout, hasPermission } = useAuth(); const [requests, setRequests] = useState<AssetStatusChangeRequest[]>([]); const [message, setMessage] = useState("Đang tải...");
  const load = useCallback(async () => { const result = await listPendingAssetStatusRequests(); if (!result.ok) return setMessage(result.error); setRequests(result.data.requests ?? []); setMessage(""); }, []);
  useEffect(() => { if (loading) return; if (!user) return void router.push("/login"); if (!hasPermission("asset.manage")) return void router.push("/assets"); const timer = setTimeout(() => void load(), 0); return () => clearTimeout(timer); }, [loading, user, router, hasPermission, load]);
  const review = async (id: string, decision: "approve" | "reject") => { const result = await reviewAssetStatusRequest(id, decision); if (!result.ok) return setMessage(result.error); void load(); };
  return <main className="min-h-screen bg-slate-50 p-3 text-slate-900 sm:p-6"><div className="mx-auto max-w-7xl lg:grid lg:grid-cols-[260px_1fr] lg:gap-4"><div><AppNav currentPath="/assets/status-requests" userLabel={`${user?.full_name ?? ""} (${user?.role_name ?? ""})`} onLogout={logout} /></div><div><header className="mb-4"><p className="text-xs font-bold uppercase tracking-[0.14em] text-orange-700">Quản lý tài sản</p><h1 className="mt-1 text-2xl font-bold">Duyệt đề xuất đổi tình trạng</h1></header>{message ? <p className="mb-3 text-sm text-slate-600">{message}</p> : null}<section className="divide-y divide-slate-100 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm">{requests.map((request) => <article key={request.id} className="py-4 first:pt-0 last:pb-0"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">{request.requested_status === "broken" ? "Đề xuất đánh dấu hỏng" : "Đề xuất đưa vào bảo trì"}</h2><p className="mt-1 text-sm text-slate-600">{request.reason}</p><p className="mt-1 text-xs text-slate-400">{request.asset_id} · {request.requester_id}</p></div><div className="flex gap-2"><button type="button" onClick={() => void review(request.id, "reject")} className="rounded-lg border border-rose-300 px-3 py-2 text-sm font-semibold text-rose-800">Từ chối</button><button type="button" onClick={() => void review(request.id, "approve")} className="rounded-lg bg-emerald-600 px-3 py-2 text-sm font-semibold text-white">Duyệt</button></div></div></article>)}{requests.length === 0 && !message ? <p className="py-8 text-center text-sm text-slate-500">Không có đề xuất chờ duyệt.</p> : null}</section></div></div></main>;
}
